# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 01f2beafb77904bdf0fb424a51c7c1c1dd9600d82ab97a5bc231690dc59a9643cbec955e53dd34463bdd72330090c982cd45877fe7cc1255888d6abe5ec419fb

test:
  secret_key_base: 3202ac3b902cdf07d4aa26e46f959950c1ec681dab07136747a59559a3b0b6d9955a9bdef1eeba0a3bd2b409b735e4e4119a94d95b12bef93dce2265d3f15b64

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
